name: Frontend Docker Image (arm32v7)

on:
  workflow_dispatch:  # Manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx (required for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub (or another registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push the Docker image for arm32v7
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/scan-shelf:arm32v7
            ${{ secrets.DOCKER_USERNAME }}/scan-shelf:frontend
            ${{ secrets.DOCKER_USERNAME }}/scan-shelf:latest
          platforms: linux/arm/v7