name: Docker Image Nextjs ARM32

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [arm32]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build ARM32 Docker image
      run: |
       docker buildx create --use 
       docker buildx build --platform linux/arm/v7 -t ${{ secrets.DOCKER_USERNAME }}/scan-shelf:latest -t ${{ secrets.DOCKER_USERNAME }}/scan-shelf:frontend --push .